config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'home#index', as: 'root'
  resources :users do
    resources :avatars, only: [:create]
    resources :collection, only: [:index]
    resources :wishlist, only: [:index]
    resources :orders, only: [:index]
    resources :ads, only: [:index]
  end

  resources :marketplaces, only: %i[index show]

  get '/KitUI', to: 'demo#show'

  resources :albums

  get 'carts/:id' => 'carts#show', as: 'cart'
  get 'carts/show'
  delete 'carts/:id' => 'carts#destroy'

  post 'cartlines' => 'cartlines#create'
  get 'cartlines/:id' => 'cartlines#show', as: 'cartline'
  delete 'cartlines/:id' => 'cartlines#destroy', as: 'cartline_destroy'

  post 'add_wishlist' => 'collection#add_to_wishlist'
  delete 'remove_wishlist' => 'collection#remove_from_wishlist'

  post 'add_collection' => 'collection#add_to_collection'
  delete 'remove_collection' => 'collection#remove_from_collection'

  patch 'to_sell' => 'collection#sell_owned_album'
  patch 'unsell_album' => 'collection#unsell_owned_album'

  resources :releases, only: %i[index show]
  get '/search/:id', to: 'releases#search', as: 'search'

  # Stripe routes
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord

  after_create :welcome_send
  paginates_per 10

  has_one_attached :avatar

  validates :avatar, attached: false, content_type: [:png, :jpg, :jpeg]
      # Include default devise modules. Others available are:
  # ,:confirmable, :lockable, :timeoutable, :trackable and :omniauthable




  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :collections, dependent: :destroy
  has_many :albums, through: :collections

  has_many :orders, dependent: :destroy

  validate :password_complexity

  def password_complexity
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    errors.add :password, 'Veuillez inclure : 1 lettre capitale, 1 lettre minuscule, 1 chiffre and 1 caractère spécial'
  end


  def order_send
    UserMailer.order_send(self).deliver_now
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include UsersHelper
  before_action :set_user, only: %i[show edit update destroy]
  before_action :is_admin?, only: %i[index]
  before_action :verify_user?, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all.page(params[:page])
  end

  # GET /users/1 or /users/1.json
  def show
    @albums = @user.albums
    @orders = Order.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.avatar.attach(params[:avatar])
    if @user.save
      redirect_to user_url(@user), notice: 'Utilisateur créé avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if @user.update!(user_params)
      redirect_to user_url(@user), notice: 'Utilisateur édité avec succès.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Utilisateur supprimé.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :address, :zip_code, :city_name, :country, :phone, :avatar)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<div class ="d-flex justify-content-start">
<%= link_to "Retour à Mon profil", @user, class: 'btn' %>
<%= render partial: "layouts/button_back_home" %>
</div>

<div class='row'>
  <div class='col-lg-6'>
  <h3 class="mt-4">Editer l'utilisateur</h3>
    <%= form_with(model: user) do |form| %>
      <% if user.errors.any? %>
        <div style="color: red">
          <h3><%= pluralize(user.errors.count, "error") %> interdit l'enregistrement de cet utilisateur :</h3>
          <ul>
            <% user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class= 'mt-4'>
        <%= form.label :Prénom, style: "display: block" %>
        <%= form.text_field :first_name, class: 'form-control' %>
      </div>
      <div class= 'mt-4'>
        <%= form.label :nom, style: "display: block" %>
        <%= form.text_field :last_name, class: 'form-control' %>
      </div>
      <div class= 'mt-4'>
        <%= form.label :adresse, style: "display: block" %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>
      <div class= 'mt-4'>
        <%= form.label :code_postal, style: "display: block" %>
        <%= form.text_field :zip_code, class: 'form-control' %>
      </div>
      <div class= 'mt-4'>
        <%= form.label :ville, style: "display: block" %>
        <%= form.text_field :city_name, class: 'form-control' %>
      </div>
      <div class= 'mt-4'>
        <%= form.label :pays, style: "display: block" %>
        <%= form.text_field :country, class: 'form-control' %>
      </div>
      <div class= 'mt-4'>
        <%= form.label :téléphone, style: "display: block" %>
        <%= form.text_field :phone, class: 'form-control' %>
      </div>
      <%= form.submit "Mettre à jour", class: 'btn btn-form mt-4' %>
    <% end %>
    </div>
    <div class= 'col-lg-4 mt-4'>
      <h3>Changer d'avatar ?</h3>
      <a>Format accepté : png, jpg</a>
      <%= form_tag user_avatars_path(@user), multipart: true do %>
        <%= file_field_tag :avatar, class: 'form-control mt-5' %>
        <%= submit_tag "Mettre à jour", class: 'btn btn-form mt-2' %>
      <% end %>
    </div>
  </div>
  <div class='mt-4'>
     <%= render partial: 'devise/registrations/edit_user' %>
     </div>
</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Prénom :</strong>
    <%= user.first_name %>
  </p>
  <p>
    <strong>Nom :</strong>
    <%= user.last_name %>
  </p>
  <p>
    <strong>Adresse :</strong>
    <%= user.address %>
  </p>
  <p>
    <strong>Code Postal :</strong>
    <%= user.zip_code %>
  </p>
  <p>
    <strong>Ville :</strong>
    <%= user.city_name %>
  </p>
  <p>
    <strong>Pays :</strong>
    <%= user.country %>
  </p>
  <p>
    <strong>Téléphone :</strong>
    <%= user.phone %>
  </p>
  <% if action_name == "index" %>
    <p>
      <%= link_to "Profil de l'utilisateur", user, class: 'btn btn-info' %>
    </p>
  <%end%>
  <hr>
  <div>
    <% if current_user.is_admin == true %>
      <%= link_to "Tous les utilisateurs", users_path, class: 'btn' %>
    <% end %>
    <%= link_to "Editer les informations", edit_user_path(user), class: 'btn btn-form' %>
    <%= button_to "Supprimer l'utilisateur", user, method: :delete, class: 'btn btn-danger' %>
    <%= render partial: "layouts/button_back_home" %>
  </div>
</div>

app/views/users/edit.html.erb
<br>
<div class="container">

<%= render partial: "users/form", layout: "shared/card_layout", locals: {user: @user} %>

<br>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <div class= "row">
    <div class= "col-sm-4">
      <h1>Les utilisateurs</h1>
    </div>
  </div>
  <div id="users">
    <% @users.each do |user| %>
      <%= render partial: 'users/user', layout: 'shared/card_layout', locals: {user: user} %>
      <%= render partial: 'shared/divider'%>
    <% end %>
    <%= paginate @users%>
  </div>
</div>

app/views/users/new.html.erb
<h1>Entrez les informations pour procéder au paiement</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Retour", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>
<h1>Mon profil</h1>
    <h2> Mes informations </h2>
    <%= render partial: "users/user", layout: "shared/card_layout", locals: {user: @user} %>