config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'home#index', as: 'root'
  resources :users do
    resources :avatars, only: [:create]
    resources :collection, only: [:index]
    resources :wishlist, only: [:index]
    resources :orders, only: [:index]
    resources :ads, only: [:index]
  end

  resources :marketplaces, only: %i[index show]

  get '/KitUI', to: 'demo#show'

  resources :albums

  get 'carts/:id' => 'carts#show', as: 'cart'
  get 'carts/show'
  delete 'carts/:id' => 'carts#destroy'

  post 'cartlines' => 'cartlines#create'
  get 'cartlines/:id' => 'cartlines#show', as: 'cartline'
  delete 'cartlines/:id' => 'cartlines#destroy', as: 'cartline_destroy'

  post 'add_wishlist' => 'collection#add_to_wishlist'
  delete 'remove_wishlist' => 'collection#remove_from_wishlist'

  post 'add_collection' => 'collection#add_to_collection'
  delete 'remove_collection' => 'collection#remove_from_collection'

  patch 'to_sell' => 'collection#sell_owned_album'
  patch 'unsell_album' => 'collection#unsell_owned_album'

  resources :releases, only: %i[index show]
  get '/search/:id', to: 'releases#search', as: 'search'

  # Stripe routes
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_add_to_cart.html.erb
<%= button_to cartlines_path(:collection_id => collection.id), class: 'btn btn-cart' do %>
  <i class="bi bi-cart-fill" style= 'color: black'></i> Ajouter au panier
<% end %>

app/views/shared/_card_layout.html.erb
 <div class="card">
    <%= yield%>
  </div>

app/views/shared/_collection_button.html.erb
<%= button_to "  Ajouter à ma collection", add_collection_path(:release_id => @release.id, :image_url => @release.images[0].uri, :title => @release.title, :artist => @release.artists[0].name, :year => @release.year), class: 'bi bi-vinyl btn btn-cart' %>

app/views/shared/_copy.html.erb
<div class = "row", data-turbo="false">
  <div class = "col-sm-3 col-md-6 col-lg-3">
    <%= image_tag(collection.album.image_url, :size => "200x200", alt: "album") %>
    <% if controller_name == "marketplaces" && current_user != collection.user %>
      <%= render partial: "shared/add_to_cart", locals: {collection: collection} %>
    <%end%>
    <% if action_name == "show" %>
      <%= link_to "Retour à toutes les annonces", marketplaces_path, class: 'btn' %>
    <% end %>
    <% if controller_name == 'wishlist' && current_user == collection.user %>
      <%= render partial: 'shared/remove_wished', locals: {collection: collection} %>
    <%end%>
    <% if controller_name == "collection" && current_user == collection.user %>
      <%= render partial: 'shared/remove_collection', locals: {collection: collection} %>
    <%end%>
    <% if controller_name == "collection" && current_user == collection.user && collection.pas_en_vente? %>
      <%= render partial: 'shared/sell_button', locals: {collection: collection} %>
    <%end%>
     <% if controller_name == "ads" && current_user == collection.user %>
      <%= render partial: 'shared/unsell_button', locals: {collection: collection} %>
    <%end%>
  </div>
  <div class="col-sm-4 col-md-6 col-lg-4">
    <div class="card-header ">
      <h3 class="card-title"> <%= collection.album.title %></h3>
      <h5 class="card-title">  <%= collection.album.artist %> - <%= collection.album.year %></h5>
      <h4 class="card-title"> <strong>€ <%= collection.album.price %></strong></h4>
      <%= render partial: "shared/link_release", locals: {collection: collection} %>
    </div>
  </div>
  <% if controller_name == "albums" && action_name == "show" %>
    <div class="col-sm-3">
      <button class="myaccordion">Labels</button>
      <div class="mypanel">
        <br>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        <br>
      </div>
    </div>
  <% end %>
  <div class="col-sm-4">
    <button class="myaccordion">Vendeur</button>
    <div class="mypanel">
      <br>
      <p><%= collection.user.first_name%> <%= collection.user.last_name%> </p>
      <br>
    </div>
    <button class="myaccordion">Etat de l'album</button>
    <div class="mypanel">
      <br>
      <p><strong>Etat de la pochette : </strong> <%= collection.sleeve_condition.gsub("_", " ").capitalize %></p>
      <p><strong>Etat du vinyl : </strong> <%= collection.media_condition.gsub("_", " ").capitalize%> </p>
      <br>
    </div>
  </div>
</div>

app/views/shared/_cover.html.erb
<div class="d-flex justify-content-center">
  <div class="flip-card text-center">
    <div class="flip-card-inner">
      <div class="flip-card-front">
        <%= image_tag(album.image_url, :size => "200x200", alt: "pochette album") %>
      </div>
      <div class="flip-card-back flip-card-back-image">
        <h5 class="mt-5 h5-flip"><%= album.title %></h5>
        <h6 class="h6-flip"><%= album.artist %></h6>
        <p><%= link_to "Plus d'info", release_path(album.release_id), class: 'btn btn-info mt-2'%></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_divider.html.erb
<br>

app/views/shared/_line_divider.html.erb
<hr>

app/views/shared/_link_release.html.erb
<%= link_to release_path(collection.album.release_id), class: "btn btn-info" do %>
 <i class="bi bi-eye"></i> En savoir plus
<% end %>

app/views/shared/_marketplace_button.html.erb
<%= link_to marketplaces_path, class: "btn btn-marketplace" do %>
  <i class="bi bi-shop icon-marketplace"></i> Marketplace
<% end %>

app/views/shared/_remove_collection.html.erb
<%= button_to "Retirer de ma collection", remove_collection_path(album_id: collection.album.id, user_id: params[:user_id]), method: :delete, class: 'btn btn-danger', data: { confirm: 'Êtes-vous sûr ?' } %>

app/views/shared/_remove_wished.html.erb
<%= button_to "Retirer de ma wishlist", remove_wishlist_path(album_id: collection.album.id, user_id: params[:user_id]), method: :delete, class: 'btn btn-danger', data: { confirm: 'Êtes-vous sûr ?' } %>

app/views/shared/_sell_button.html.erb
<%= button_to "Vendre cet album", to_sell_path(album_id: collection.album.id, user_id: params[:user_id]), method: :patch, class: 'btn btn-form', data: { confirm: 'Êtes-vous sûr ?' } %>

app/views/shared/_unsell_button.html.erb
<%= button_to "Ne plus vendre cet album", unsell_album_path(album_id: collection.album.id, user_id: params[:user_id]), method: :patch, class: 'btn btn-danger', data: { confirm: 'Êtes-vous sûr ?' } %>

app/views/shared/_wishlist_button.html.erb
<%= button_to "Ajouter à ma wishlist", add_wishlist_path(:release_id => @release.id, :image_url => @release.images[0].uri, :title => @release.title, :artist => @release.artists[0].name, :year => @release.year), class: 'btn btn-cart bi bi-bookmark-star' %>