config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'home#index', as: 'root'
  resources :users do
    resources :avatars, only: [:create]
    resources :collection, only: [:index]
    resources :wishlist, only: [:index]
    resources :orders, only: [:index]
    resources :ads, only: [:index]
  end

  resources :marketplaces, only: %i[index show]

  get '/KitUI', to: 'demo#show'

  resources :albums

  get 'carts/:id' => 'carts#show', as: 'cart'
  get 'carts/show'
  delete 'carts/:id' => 'carts#destroy'

  post 'cartlines' => 'cartlines#create'
  get 'cartlines/:id' => 'cartlines#show', as: 'cartline'
  delete 'cartlines/:id' => 'cartlines#destroy', as: 'cartline_destroy'

  post 'add_wishlist' => 'collection#add_to_wishlist'
  delete 'remove_wishlist' => 'collection#remove_from_wishlist'

  post 'add_collection' => 'collection#add_to_collection'
  delete 'remove_collection' => 'collection#remove_from_collection'

  patch 'to_sell' => 'collection#sell_owned_album'
  patch 'unsell_album' => 'collection#unsell_owned_album'

  resources :releases, only: %i[index show]
  get '/search/:id', to: 'releases#search', as: 'search'

  # Stripe routes
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cartlines, dependent: :destroy
  has_many :collections, through: :cartlines
  has_one :order

  def sub_total
    sum = 0
    cartlines.each do |cartline|
      sum += cartline.collection.album.price
    end
    sum
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show
    @cart = @current_cart
    @cartlines = @cart.cartlines
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to cart_path
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/_cartline.html.erb
<%= render partial: 'shared/copy', locals: {collection: cartline.collection } %>
<%= button_to "Retirer l'album du panier", cartline_destroy_path(cartline.id), method: :delete, class: 'btn btn-danger' %>

app/views/carts/_total.html.erb
<% if cart.sub_total != 0 %>
  <h3>Total : <%= number_to_currency(cart.sub_total, :locale => :fr) %></h3>
  <%= button_to "Paiement", checkout_create_path(total: cart.sub_total), class: "btn btn-primary", remote: true, class: "btn btn-success", "data-turbo" => "false" %>
  <br>
  <hr>
  <%= button_to "Vider le panier", cart_path(@current_cart),method: :delete, data: {confirm: "Êtes-vous sur ?"}, class: 'btn btn-warning' %>
<% else %>
  <a>Votre panier est vide</a>
  <%= render 'shared/marketplace_button' %>
<% end %>

app/views/carts/show.html.erb
<div class='container'>
  <h2>Mon panier</h2>
  <div class="row">
    <div class="col-sm-8">
      <%= render partial: "carts/cartline", layout: 'shared/card_layout', collection: @cartlines, spacer_template: 'shared/divider' %>
    </div>
    <div class="col-sm-3">
      <%= render partial: "carts/total", locals: {cart: @cart}, layout: 'shared/card_layout'%>
    </div>
  </div>
</div>